name: Test github action on frontend project

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./src/'Expense Tracker' # Adjust if your package.json is not in the src directory

    - name: Check Node.js version
      run: node -v

    - name: Run tests
      run: npm test
      working-directory: ./src/'Expense Tracker'
