name: My First Github Actions project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    startegy:
      matrix:
        python-version: [3.8, 3.9] # define the versions on which you want to run your code

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py
